### PR TITLE
Import Swagger YAML files.

### PR DESCRIPTION
**Pull request by fabiocognigni**
The Swagger Java parser accepts both YAML and JSON files content.
This addresses #585 

Notes:
- tried https://gist.github.com/earth2marsh/264123aefc2e29551d9d but it doesn't seem a good spec (note all $ref doesn't have `#/defintions/` prefix);
- [this](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/uber.yaml) seems to fix it but still apidoc can't import it: I can reproduce the same error with the same spec in JSON format (translated using swaggerhub) so I believe the issue doesn't depend on these changes but it's more deep in the swagger integration regardless of the swagger format - troubleshooting was taking too long so I'll probably open a new issue for this;
- tests with YAML versions of JSON specs that were correctly imported looks fine.

### CODE REVIEW

**Comment by mbryzek** [comment]
lgtm

**Comment by fabiocognigni** [comment]
@mbryzek this is now completed

**Comment by mbryzek** [comment]
nice! merging

**Comment by mbryzek** [comment]
now live

**Pull request merged**
