### PR TITLE
Specify request and response headers as part of an operation

### PR DESCRIPTION
**Pull request by gheine**

### CODE REVIEW

**Comment by gheine** [comment]
Not happy with this solution. I believe #524 is the better approach.

**Comment by gheine** [comment]
@mbryzek this should be compatible with the swagger spec now, see http://swagger.io/specification/. 

Can we deprecate global (service-level) headers?

**Comment by Seanstoppable** [comment]
Nice!

**Comment by gheine** [comment]
@mbryzek do you think this is good to go?

**Comment by gheine** [comment]
The test failure appears to be spurious

**Pull request merged**
