### PR TITLE
Custom attributes implementation - v2

### PR DESCRIPTION
**Pull request by kalmanb**
Should be a full implemenation now. Diffs for model and field have tests, others don't.

I've run this up locally and tested our generators, seems good.

Note thet attributes are manditory on the service spec. This has quite an impact on testing, esp `apidoc-generator`. It means that every model, field, enum etc has to have attributes defined. We should probably hold off merging this until the generator tests have been updated - it's quite a big update. I'll see if I can get it done tomorrow. I did this a while back for our fork of the generators, I'll pull in that patch.

Sorry that it's a third PR, seemed cleaner.

### CODE REVIEW

**Comment by kalmanb** [comment]
Travis is setting up the user `web` instead of `api` and failing the build, same in master - had the problem locally too.
Need to update the travis build.

**Comment by mbryzek** [comment]
Looks great. I'm testing on my own local branch where I've rebased off master... hoping to merge tonight

**Comment by mbryzek** [comment]
I've merged into master (though I did off local branch after rebasing and
testing) and should be live shortly

All looked great. Couple notes:

  - travis build should be fixed - sorry about that
  - we will need to update www.apidoc.me/doc/apiJson when ready to document
the attributes
  - the production generator works just fine with this change (there is
nothing that needs to be done) - and thus have merged tonight rather than
waiting. We can update the generator on its own schedule.
  - I like how you defined the attribute.value as type object - I'll plan
to change the org level attributes to json as well to be consistent.

Mike

**Comment by mbryzek** [comment]
Have merged through command line  and closing PR

**Pull request closed without merging**
