### PR TITLE
Specify request and response headers as part of an operation

### PR DESCRIPTION
**Pull request by gheine**

### CODE REVIEW

**Comment by gheine** [comment]
This impl allows required/non-required overrides of headers per operation (so a header "foo" could be required for one and optional for another operation) via the header_ref type. If we don't think that is beneficial, we could use the required field of the header type and the operation would just need two string array fields (request_headers and response_headers) that contain the by-name references to the respective headers, like:
```
    {
      "name": "Api Doc",
      "headers": [
        { "name": "foo", "type": "string", "required": "false" },
        { "name": "bar", "type": "string", "required": "true"}
      ],
      "resources": {
        "user": {
          "operations": [
            {
              "request_headers": [ "foo" ],
              "response_headers": [ "bar" ]
            }
          ]
        }
      }
    }
```

**Comment by mbryzek** [comment]
looking good - one question given the priority to build out compatibility w/ swagger - do you know if this is compatible w/ swagger? if not would it make sense to just adopt their header spec?

**Comment by gheine** [comment]
Good point @mbryzek. Swagger does not have a global headers definition like apidoc and instead defines them on the operation, similar to what I did in PR #520. What I didn't get right here is actually that different responses can have different headers, so instead of a response_headers definition on the operation, there should be a headers definition on the response type. 

Swinging back to the approach in #520, how about we separate the per-operation headers from the global per-api headers and define them as parameters with a new parameter location type for the request and as a headers: [header] field on the response? 

In the long run, we can maybe deprecate the global headers field?

**Comment by gheine** [comment]
Moved conversation back to #520

**Pull request closed without merging**
